### ISSUE TITLE
Vortran lasers need to report fault code

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/coPylot#178]
Vortran lasers should report a fault code and fault description such that it can be processed by downstream software - e.g. there is no point in turning on laser emission if the interlock is open. This could be implemented at a `status` command which returns a tuple of `(fault_code, fault_descriptin)`.

<img width="633" alt="Screenshot 2023-09-06 at 12 24 49 PM" src="https://github.com/czbiohub-sf/coPylot/assets/11934632/b72189e1-3388-4fbe-99bf-aa8a9d5c76aa">

**Comment by edyoshikun** [comment]
upon re-reading the documentation, we also have `?FD` which returns the description.  Instead of making a dictionary with the fault codes and descriptions, I can call `?FC` and `?FD`. 

![Screenshot 2023-09-06 at 12 58 20 PM](https://github.com/czbiohub-sf/coPylot/assets/10470962/3c8c0a4f-cdba-4074-96e4-b41a3469c83c)

**Comment by ieivanov** [comment]
P.S. this is not a blocker
